// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATmNFBOfyIgbLvZ7BnfFDEFWAkMWPKqQ',
    appId: '1:136225829076:web:f84befc11ceb7e1cddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    authDomain: 'base-pro-b0a43.firebaseapp.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5DO4_wjh4w2R0rol_UgYOFrbP-FM6XM',
    appId: '1:136225829076:android:9c93a16aabe9376addcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    storageBucket: 'base-pro-b0a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGBUKYPVRXUmuyo-hf4kShyYmDxD4_4c',
    appId: '1:136225829076:ios:fe563eb1be70d45fddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    storageBucket: 'base-pro-b0a43.appspot.com',
    iosBundleId: 'com.example.realProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGBUKYPVRXUmuyo-hf4kShyYmDxD4_4c',
    appId: '1:136225829076:ios:fe563eb1be70d45fddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    storageBucket: 'base-pro-b0a43.appspot.com',
    iosBundleId: 'com.example.realProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATmNFBOfyIgbLvZ7BnfFDEFWAkMWPKqQ',
    appId: '1:136225829076:web:e5f440133e3f541fddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    authDomain: 'base-pro-b0a43.firebaseapp.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
  );

}